# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TCMon.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 531)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Painel = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Painel.sizePolicy().hasHeightForWidth())
        self.Painel.setSizePolicy(sizePolicy)
        self.Painel.setMinimumSize(QtCore.QSize(200, 0))
        self.Painel.setObjectName("Painel")
        self.gridLayout = QtWidgets.QGridLayout(self.Painel)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.Painel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 4)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkE1 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkE1.sizePolicy().hasHeightForWidth())
        self.checkE1.setSizePolicy(sizePolicy)
        self.checkE1.setObjectName("checkE1")
        self.gridLayout_4.addWidget(self.checkE1, 0, 0, 1, 1)
        self.checkE2 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkE2.sizePolicy().hasHeightForWidth())
        self.checkE2.setSizePolicy(sizePolicy)
        self.checkE2.setObjectName("checkE2")
        self.gridLayout_4.addWidget(self.checkE2, 2, 0, 1, 1)
        self.valE2 = QtWidgets.QLabel(self.groupBox)
        self.valE2.setAutoFillBackground(False)
        self.valE2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valE2.setFrameShape(QtWidgets.QFrame.Box)
        self.valE2.setLineWidth(1)
        self.valE2.setAlignment(QtCore.Qt.AlignCenter)
        self.valE2.setObjectName("valE2")
        self.gridLayout_4.addWidget(self.valE2, 0, 1, 1, 1)
        self.valE1 = QtWidgets.QLabel(self.groupBox)
        self.valE1.setAutoFillBackground(False)
        self.valE1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valE1.setFrameShape(QtWidgets.QFrame.Box)
        self.valE1.setLineWidth(1)
        self.valE1.setAlignment(QtCore.Qt.AlignCenter)
        self.valE1.setObjectName("valE1")
        self.gridLayout_4.addWidget(self.valE1, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 11, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Painel)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setContentsMargins(2, 2, 2, 4)
        self.gridLayout_7.setSpacing(2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.comboPorta = QtWidgets.QComboBox(self.groupBox_3)
        self.comboPorta.setObjectName("comboPorta")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.comboPorta.addItem("")
        self.gridLayout_7.addWidget(self.comboPorta, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 0, 1, 1)
        self.comboAmostragem = QtWidgets.QComboBox(self.groupBox_3)
        self.comboAmostragem.setObjectName("comboAmostragem")
        self.comboAmostragem.addItem("")
        self.comboAmostragem.addItem("")
        self.comboAmostragem.addItem("")
        self.comboAmostragem.addItem("")
        self.comboAmostragem.addItem("")
        self.comboAmostragem.addItem("")
        self.comboAmostragem.addItem("")
        self.comboAmostragem.addItem("")
        self.comboAmostragem.addItem("")
        self.comboAmostragem.addItem("")
        self.gridLayout_7.addWidget(self.comboAmostragem, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 2, 0, 1, 1)
        self.comboTipoTermopar = QtWidgets.QComboBox(self.groupBox_3)
        self.comboTipoTermopar.setObjectName("comboTipoTermopar")
        self.comboTipoTermopar.addItem("")
        self.comboTipoTermopar.addItem("")
        self.comboTipoTermopar.addItem("")
        self.comboTipoTermopar.addItem("")
        self.comboTipoTermopar.addItem("")
        self.comboTipoTermopar.addItem("")
        self.comboTipoTermopar.addItem("")
        self.comboTipoTermopar.addItem("")
        self.gridLayout_7.addWidget(self.comboTipoTermopar, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 13, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 22, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Painel)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setContentsMargins(2, 2, 2, 4)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.valT6 = QtWidgets.QLabel(self.groupBox_2)
        self.valT6.setAutoFillBackground(False)
        self.valT6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valT6.setFrameShape(QtWidgets.QFrame.Box)
        self.valT6.setLineWidth(1)
        self.valT6.setAlignment(QtCore.Qt.AlignCenter)
        self.valT6.setObjectName("valT6")
        self.gridLayout_5.addWidget(self.valT6, 6, 1, 1, 1)
        self.valT7 = QtWidgets.QLabel(self.groupBox_2)
        self.valT7.setAutoFillBackground(False)
        self.valT7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valT7.setFrameShape(QtWidgets.QFrame.Box)
        self.valT7.setLineWidth(1)
        self.valT7.setAlignment(QtCore.Qt.AlignCenter)
        self.valT7.setObjectName("valT7")
        self.gridLayout_5.addWidget(self.valT7, 7, 1, 1, 1)
        self.checkT7 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkT7.sizePolicy().hasHeightForWidth())
        self.checkT7.setSizePolicy(sizePolicy)
        self.checkT7.setObjectName("checkT7")
        self.gridLayout_5.addWidget(self.checkT7, 7, 0, 1, 1)
        self.valT8 = QtWidgets.QLabel(self.groupBox_2)
        self.valT8.setAutoFillBackground(False)
        self.valT8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valT8.setFrameShape(QtWidgets.QFrame.Box)
        self.valT8.setLineWidth(1)
        self.valT8.setAlignment(QtCore.Qt.AlignCenter)
        self.valT8.setObjectName("valT8")
        self.gridLayout_5.addWidget(self.valT8, 8, 1, 1, 1)
        self.checkT8 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkT8.sizePolicy().hasHeightForWidth())
        self.checkT8.setSizePolicy(sizePolicy)
        self.checkT8.setObjectName("checkT8")
        self.gridLayout_5.addWidget(self.checkT8, 8, 0, 1, 1)
        self.valT2 = QtWidgets.QLabel(self.groupBox_2)
        self.valT2.setAutoFillBackground(False)
        self.valT2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valT2.setFrameShape(QtWidgets.QFrame.Box)
        self.valT2.setLineWidth(1)
        self.valT2.setAlignment(QtCore.Qt.AlignCenter)
        self.valT2.setObjectName("valT2")
        self.gridLayout_5.addWidget(self.valT2, 2, 1, 1, 1)
        self.valT3 = QtWidgets.QLabel(self.groupBox_2)
        self.valT3.setAutoFillBackground(False)
        self.valT3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valT3.setFrameShape(QtWidgets.QFrame.Box)
        self.valT3.setLineWidth(1)
        self.valT3.setAlignment(QtCore.Qt.AlignCenter)
        self.valT3.setObjectName("valT3")
        self.gridLayout_5.addWidget(self.valT3, 3, 1, 1, 1)
        self.checkT4 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkT4.sizePolicy().hasHeightForWidth())
        self.checkT4.setSizePolicy(sizePolicy)
        self.checkT4.setObjectName("checkT4")
        self.gridLayout_5.addWidget(self.checkT4, 4, 0, 1, 1)
        self.checkT3 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkT3.sizePolicy().hasHeightForWidth())
        self.checkT3.setSizePolicy(sizePolicy)
        self.checkT3.setObjectName("checkT3")
        self.gridLayout_5.addWidget(self.checkT3, 3, 0, 1, 1)
        self.checkT1 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkT1.sizePolicy().hasHeightForWidth())
        self.checkT1.setSizePolicy(sizePolicy)
        self.checkT1.setObjectName("checkT1")
        self.gridLayout_5.addWidget(self.checkT1, 1, 0, 1, 1)
        self.valT4 = QtWidgets.QLabel(self.groupBox_2)
        self.valT4.setAutoFillBackground(False)
        self.valT4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valT4.setFrameShape(QtWidgets.QFrame.Box)
        self.valT4.setLineWidth(1)
        self.valT4.setAlignment(QtCore.Qt.AlignCenter)
        self.valT4.setObjectName("valT4")
        self.gridLayout_5.addWidget(self.valT4, 4, 1, 1, 1)
        self.valT1 = QtWidgets.QLabel(self.groupBox_2)
        self.valT1.setAutoFillBackground(False)
        self.valT1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valT1.setFrameShape(QtWidgets.QFrame.Box)
        self.valT1.setLineWidth(1)
        self.valT1.setAlignment(QtCore.Qt.AlignCenter)
        self.valT1.setObjectName("valT1")
        self.gridLayout_5.addWidget(self.valT1, 1, 1, 1, 1)
        self.checkT2 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkT2.sizePolicy().hasHeightForWidth())
        self.checkT2.setSizePolicy(sizePolicy)
        self.checkT2.setObjectName("checkT2")
        self.gridLayout_5.addWidget(self.checkT2, 2, 0, 1, 1)
        self.checkT5 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkT5.sizePolicy().hasHeightForWidth())
        self.checkT5.setSizePolicy(sizePolicy)
        self.checkT5.setObjectName("checkT5")
        self.gridLayout_5.addWidget(self.checkT5, 5, 0, 1, 1)
        self.valT5 = QtWidgets.QLabel(self.groupBox_2)
        self.valT5.setAutoFillBackground(False)
        self.valT5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valT5.setFrameShape(QtWidgets.QFrame.Box)
        self.valT5.setLineWidth(1)
        self.valT5.setAlignment(QtCore.Qt.AlignCenter)
        self.valT5.setObjectName("valT5")
        self.gridLayout_5.addWidget(self.valT5, 5, 1, 1, 1)
        self.checkT6 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkT6.sizePolicy().hasHeightForWidth())
        self.checkT6.setSizePolicy(sizePolicy)
        self.checkT6.setObjectName("checkT6")
        self.gridLayout_5.addWidget(self.checkT6, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.valRef = QtWidgets.QLabel(self.groupBox_2)
        self.valRef.setAutoFillBackground(False)
        self.valRef.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valRef.setFrameShape(QtWidgets.QFrame.Box)
        self.valRef.setLineWidth(1)
        self.valRef.setAlignment(QtCore.Qt.AlignCenter)
        self.valRef.setObjectName("valRef")
        self.gridLayout_5.addWidget(self.valRef, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.grupoControle = QtWidgets.QGroupBox(self.Painel)
        self.grupoControle.setAlignment(QtCore.Qt.AlignCenter)
        self.grupoControle.setFlat(False)
        self.grupoControle.setObjectName("grupoControle")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.grupoControle)
        self.gridLayout_6.setContentsMargins(2, 2, 2, 4)
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkCtrlAuto = QtWidgets.QCheckBox(self.grupoControle)
        self.checkCtrlAuto.setObjectName("checkCtrlAuto")
        self.gridLayout_6.addWidget(self.checkCtrlAuto, 2, 0, 1, 1)
        self.spinCtrlManual = QtWidgets.QSpinBox(self.grupoControle)
        self.spinCtrlManual.setMaximum(100)
        self.spinCtrlManual.setObjectName("spinCtrlManual")
        self.gridLayout_6.addWidget(self.spinCtrlManual, 1, 1, 1, 1)
        self.valPower = QtWidgets.QLabel(self.grupoControle)
        self.valPower.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valPower.setFrameShape(QtWidgets.QFrame.Box)
        self.valPower.setAlignment(QtCore.Qt.AlignCenter)
        self.valPower.setObjectName("valPower")
        self.gridLayout_6.addWidget(self.valPower, 4, 0, 1, 1)
        self.comboTermoparCtrl = QtWidgets.QComboBox(self.grupoControle)
        self.comboTermoparCtrl.setObjectName("comboTermoparCtrl")
        self.comboTermoparCtrl.addItem("")
        self.comboTermoparCtrl.addItem("")
        self.comboTermoparCtrl.addItem("")
        self.comboTermoparCtrl.addItem("")
        self.comboTermoparCtrl.addItem("")
        self.comboTermoparCtrl.addItem("")
        self.comboTermoparCtrl.addItem("")
        self.comboTermoparCtrl.addItem("")
        self.gridLayout_6.addWidget(self.comboTermoparCtrl, 3, 0, 1, 1)
        self.checkCtrlManual = QtWidgets.QCheckBox(self.grupoControle)
        self.checkCtrlManual.setObjectName("checkCtrlManual")
        self.gridLayout_6.addWidget(self.checkCtrlManual, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 5, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.grupoControle)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinKp = QtWidgets.QDoubleSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinKp.sizePolicy().hasHeightForWidth())
        self.spinKp.setSizePolicy(sizePolicy)
        self.spinKp.setMinimum(-1000.0)
        self.spinKp.setMaximum(1000.0)
        self.spinKp.setProperty("value", 1.0)
        self.spinKp.setObjectName("spinKp")
        self.gridLayout_2.addWidget(self.spinKp, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 1, 1, 1)
        self.spinKd = QtWidgets.QDoubleSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinKd.sizePolicy().hasHeightForWidth())
        self.spinKd.setSizePolicy(sizePolicy)
        self.spinKd.setMinimum(-1000.0)
        self.spinKd.setMaximum(1000.0)
        self.spinKd.setProperty("value", 0.0)
        self.spinKd.setObjectName("spinKd")
        self.gridLayout_2.addWidget(self.spinKd, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 1, 1, 1)
        self.spinKi = QtWidgets.QDoubleSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinKi.sizePolicy().hasHeightForWidth())
        self.spinKi.setSizePolicy(sizePolicy)
        self.spinKi.setMinimum(-1000.0)
        self.spinKi.setMaximum(1000.0)
        self.spinKi.setObjectName("spinKi")
        self.gridLayout_2.addWidget(self.spinKi, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.widget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 0, 0, 5, 1)
        self.spinSetPoint = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.spinSetPoint.setDecimals(0)
        self.spinSetPoint.setObjectName("spinSetPoint")
        self.gridLayout_2.addWidget(self.spinSetPoint, 0, 1, 1, 2)
        self.gridLayout_6.addWidget(self.widget_3, 2, 1, 4, 1)
        self.gridLayout.addWidget(self.grupoControle, 12, 0, 1, 2)
        self.horizontalLayout.addWidget(self.Painel)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plotWidget = QtWidgets.QWidget(self.widget)
        self.plotWidget.setObjectName("plotWidget")
        self.plotWidgetLayout = QtWidgets.QVBoxLayout(self.plotWidget)
        self.plotWidgetLayout.setContentsMargins(2, 3, 2, 2)
        self.plotWidgetLayout.setSpacing(0)
        self.plotWidgetLayout.setObjectName("plotWidgetLayout")
        self.gridLayout_3.addWidget(self.plotWidget, 1, 0, 1, 1)
        self.bLimpar = QtWidgets.QPushButton(self.widget)
        self.bLimpar.setObjectName("bLimpar")
        self.gridLayout_3.addWidget(self.bLimpar, 4, 0, 1, 1)
        self.timeLabel = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        self.timeLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout_3.addWidget(self.timeLabel, 0, 0, 1, 1)
        self.bIniciar = QtWidgets.QPushButton(self.widget)
        self.bIniciar.setObjectName("bIniciar")
        self.gridLayout_3.addWidget(self.bIniciar, 3, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bPageDown = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bPageDown.sizePolicy().hasHeightForWidth())
        self.bPageDown.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.bPageDown.setFont(font)
        self.bPageDown.setObjectName("bPageDown")
        self.horizontalLayout_2.addWidget(self.bPageDown)
        self.spinJanela = QtWidgets.QSpinBox(self.widget_2)
        self.spinJanela.setAlignment(QtCore.Qt.AlignCenter)
        self.spinJanela.setPrefix("")
        self.spinJanela.setMinimum(10)
        self.spinJanela.setMaximum(1200)
        self.spinJanela.setSingleStep(10)
        self.spinJanela.setProperty("value", 120)
        self.spinJanela.setObjectName("spinJanela")
        self.horizontalLayout_2.addWidget(self.spinJanela)
        self.bPageUp = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.bPageUp.setFont(font)
        self.bPageUp.setObjectName("bPageUp")
        self.horizontalLayout_2.addWidget(self.bPageUp)
        self.gridLayout_3.addWidget(self.widget_2, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalvar_Dados = QtWidgets.QAction(MainWindow)
        self.actionSalvar_Dados.setObjectName("actionSalvar_Dados")
        self.actionPorta_Serial = QtWidgets.QAction(MainWindow)
        self.actionPorta_Serial.setObjectName("actionPorta_Serial")
        self.actionCOM1 = QtWidgets.QAction(MainWindow)
        self.actionCOM1.setObjectName("actionCOM1")
        self.actionCOM2 = QtWidgets.QAction(MainWindow)
        self.actionCOM2.setObjectName("actionCOM2")
        self.actionCOM3 = QtWidgets.QAction(MainWindow)
        self.actionCOM3.setObjectName("actionCOM3")
        self.actionCOM4 = QtWidgets.QAction(MainWindow)
        self.actionCOM4.setObjectName("actionCOM4")
        self.actionCOM5 = QtWidgets.QAction(MainWindow)
        self.actionCOM5.setObjectName("actionCOM5")
        self.actionCOM6 = QtWidgets.QAction(MainWindow)
        self.actionCOM6.setObjectName("actionCOM6")
        self.actionCOM7 = QtWidgets.QAction(MainWindow)
        self.actionCOM7.setObjectName("actionCOM7")
        self.actionCOM8 = QtWidgets.QAction(MainWindow)
        self.actionCOM8.setObjectName("actionCOM8")
        self.actionCOM9 = QtWidgets.QAction(MainWindow)
        self.actionCOM9.setObjectName("actionCOM9")
        self.actionCOM10 = QtWidgets.QAction(MainWindow)
        self.actionCOM10.setObjectName("actionCOM10")
        self.actionCOM11 = QtWidgets.QAction(MainWindow)
        self.actionCOM11.setObjectName("actionCOM11")
        self.actionCOM12 = QtWidgets.QAction(MainWindow)
        self.actionCOM12.setObjectName("actionCOM12")
        self.action1_s = QtWidgets.QAction(MainWindow)
        self.action1_s.setObjectName("action1_s")
        self.action2_s = QtWidgets.QAction(MainWindow)
        self.action2_s.setObjectName("action2_s")
        self.action3_s = QtWidgets.QAction(MainWindow)
        self.action3_s.setObjectName("action3_s")
        self.action4_s = QtWidgets.QAction(MainWindow)
        self.action4_s.setObjectName("action4_s")
        self.action5_s = QtWidgets.QAction(MainWindow)
        self.action5_s.setObjectName("action5_s")
        self.action6_s = QtWidgets.QAction(MainWindow)
        self.action6_s.setObjectName("action6_s")
        self.action7_s = QtWidgets.QAction(MainWindow)
        self.action7_s.setObjectName("action7_s")
        self.action8_s = QtWidgets.QAction(MainWindow)
        self.action8_s.setObjectName("action8_s")
        self.action9_s = QtWidgets.QAction(MainWindow)
        self.action9_s.setObjectName("action9_s")
        self.action10_s = QtWidgets.QAction(MainWindow)
        self.action10_s.setObjectName("action10_s")
        self.menuMenu.addAction(self.actionSalvar_Dados)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TCMonPy v0.2"))
        self.groupBox.setTitle(_translate("MainWindow", "Entradas Auxiliares"))
        self.checkE1.setText(_translate("MainWindow", "Entrada 1"))
        self.checkE2.setText(_translate("MainWindow", "Entrada 2"))
        self.valE2.setText(_translate("MainWindow", "0.0 V"))
        self.valE1.setText(_translate("MainWindow", "0.0 V"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Configurações"))
        self.label_8.setText(_translate("MainWindow", "Porta:"))
        self.comboPorta.setItemText(0, _translate("MainWindow", "COM1"))
        self.comboPorta.setItemText(1, _translate("MainWindow", "COM2"))
        self.comboPorta.setItemText(2, _translate("MainWindow", "COM3"))
        self.comboPorta.setItemText(3, _translate("MainWindow", "COM4"))
        self.comboPorta.setItemText(4, _translate("MainWindow", "COM5"))
        self.comboPorta.setItemText(5, _translate("MainWindow", "COM6"))
        self.comboPorta.setItemText(6, _translate("MainWindow", "COM7"))
        self.comboPorta.setItemText(7, _translate("MainWindow", "COM8"))
        self.comboPorta.setItemText(8, _translate("MainWindow", "COM9"))
        self.comboPorta.setItemText(9, _translate("MainWindow", "COM10"))
        self.comboPorta.setItemText(10, _translate("MainWindow", "COM11"))
        self.comboPorta.setItemText(11, _translate("MainWindow", "COM12"))
        self.comboPorta.setItemText(12, _translate("MainWindow", "COM13"))
        self.comboPorta.setItemText(13, _translate("MainWindow", "COM14"))
        self.comboPorta.setItemText(14, _translate("MainWindow", "COM15"))
        self.label_9.setText(_translate("MainWindow", "Amostragem:"))
        self.comboAmostragem.setItemText(0, _translate("MainWindow", "1 s"))
        self.comboAmostragem.setItemText(1, _translate("MainWindow", "2 s"))
        self.comboAmostragem.setItemText(2, _translate("MainWindow", "3 s"))
        self.comboAmostragem.setItemText(3, _translate("MainWindow", "4 s"))
        self.comboAmostragem.setItemText(4, _translate("MainWindow", "5 s"))
        self.comboAmostragem.setItemText(5, _translate("MainWindow", "6 s"))
        self.comboAmostragem.setItemText(6, _translate("MainWindow", "7 s"))
        self.comboAmostragem.setItemText(7, _translate("MainWindow", "8 s"))
        self.comboAmostragem.setItemText(8, _translate("MainWindow", "9 s"))
        self.comboAmostragem.setItemText(9, _translate("MainWindow", "10 s"))
        self.label_10.setText(_translate("MainWindow", "Tipo Termopar:"))
        self.comboTipoTermopar.setCurrentText(_translate("MainWindow", "B"))
        self.comboTipoTermopar.setItemText(0, _translate("MainWindow", "B"))
        self.comboTipoTermopar.setItemText(1, _translate("MainWindow", "E"))
        self.comboTipoTermopar.setItemText(2, _translate("MainWindow", "J"))
        self.comboTipoTermopar.setItemText(3, _translate("MainWindow", "K"))
        self.comboTipoTermopar.setItemText(4, _translate("MainWindow", "N"))
        self.comboTipoTermopar.setItemText(5, _translate("MainWindow", "R"))
        self.comboTipoTermopar.setItemText(6, _translate("MainWindow", "S"))
        self.comboTipoTermopar.setItemText(7, _translate("MainWindow", "T"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Termopares"))
        self.valT6.setText(_translate("MainWindow", "0.0 °C"))
        self.valT7.setText(_translate("MainWindow", "0.0 °C"))
        self.checkT7.setText(_translate("MainWindow", "Termopar 7"))
        self.valT8.setText(_translate("MainWindow", "0.0 °C"))
        self.checkT8.setText(_translate("MainWindow", "Termopar 8"))
        self.valT2.setText(_translate("MainWindow", "0.0 °C"))
        self.valT3.setText(_translate("MainWindow", "0.0 °C"))
        self.checkT4.setText(_translate("MainWindow", "Termopar 4"))
        self.checkT3.setText(_translate("MainWindow", "Termopar 3"))
        self.checkT1.setText(_translate("MainWindow", "Termopar 1"))
        self.valT4.setText(_translate("MainWindow", "0.0 °C"))
        self.valT1.setText(_translate("MainWindow", "0.0 °C"))
        self.checkT2.setText(_translate("MainWindow", "Termopar 2"))
        self.checkT5.setText(_translate("MainWindow", "Termopar 5"))
        self.valT5.setText(_translate("MainWindow", "0.0 °C"))
        self.checkT6.setText(_translate("MainWindow", "Termopar 6"))
        self.label_11.setText(_translate("MainWindow", "Junta Fria"))
        self.valRef.setText(_translate("MainWindow", "0.0 °C"))
        self.grupoControle.setTitle(_translate("MainWindow", "Controle"))
        self.checkCtrlAuto.setText(_translate("MainWindow", "Automático"))
        self.spinCtrlManual.setSuffix(_translate("MainWindow", "%"))
        self.valPower.setText(_translate("MainWindow", "-"))
        self.comboTermoparCtrl.setItemText(0, _translate("MainWindow", "Termopar 1"))
        self.comboTermoparCtrl.setItemText(1, _translate("MainWindow", "Termopar 2"))
        self.comboTermoparCtrl.setItemText(2, _translate("MainWindow", "Termopar 3"))
        self.comboTermoparCtrl.setItemText(3, _translate("MainWindow", "Termopar 4"))
        self.comboTermoparCtrl.setItemText(4, _translate("MainWindow", "Termopar 5"))
        self.comboTermoparCtrl.setItemText(5, _translate("MainWindow", "Termopar 6"))
        self.comboTermoparCtrl.setItemText(6, _translate("MainWindow", "Termopar 7"))
        self.comboTermoparCtrl.setItemText(7, _translate("MainWindow", "Termopar 8"))
        self.checkCtrlManual.setText(_translate("MainWindow", "Manual"))
        self.label_3.setText(_translate("MainWindow", "Ki:"))
        self.label_4.setText(_translate("MainWindow", "Kd:"))
        self.label_2.setText(_translate("MainWindow", "Kp:"))
        self.spinSetPoint.setSuffix(_translate("MainWindow", " °C"))
        self.bLimpar.setText(_translate("MainWindow", "Limpar Dados"))
        self.timeLabel.setText(_translate("MainWindow", "0 s"))
        self.bIniciar.setText(_translate("MainWindow", "Iniciar/Parar"))
        self.bPageDown.setText(_translate("MainWindow", "<<"))
        self.spinJanela.setSuffix(_translate("MainWindow", " s"))
        self.bPageUp.setText(_translate("MainWindow", ">>"))
        self.menuMenu.setTitle(_translate("MainWindow", "Arquivo"))
        self.actionSalvar_Dados.setText(_translate("MainWindow", "Salvar Dados..."))
        self.actionPorta_Serial.setText(_translate("MainWindow", "Porta Serial"))
        self.actionCOM1.setText(_translate("MainWindow", "COM1"))
        self.actionCOM2.setText(_translate("MainWindow", " COM2"))
        self.actionCOM3.setText(_translate("MainWindow", " COM3"))
        self.actionCOM4.setText(_translate("MainWindow", " COM4"))
        self.actionCOM5.setText(_translate("MainWindow", "COM5"))
        self.actionCOM6.setText(_translate("MainWindow", "COM6"))
        self.actionCOM7.setText(_translate("MainWindow", "COM7"))
        self.actionCOM8.setText(_translate("MainWindow", "COM8"))
        self.actionCOM9.setText(_translate("MainWindow", "COM9"))
        self.actionCOM10.setText(_translate("MainWindow", "COM10"))
        self.actionCOM11.setText(_translate("MainWindow", "COM11"))
        self.actionCOM12.setText(_translate("MainWindow", "COM12"))
        self.action1_s.setText(_translate("MainWindow", "1 s"))
        self.action2_s.setText(_translate("MainWindow", "2 s "))
        self.action3_s.setText(_translate("MainWindow", "3 s"))
        self.action4_s.setText(_translate("MainWindow", "4 s"))
        self.action5_s.setText(_translate("MainWindow", "5 s"))
        self.action6_s.setText(_translate("MainWindow", "6 s"))
        self.action7_s.setText(_translate("MainWindow", "7 s"))
        self.action8_s.setText(_translate("MainWindow", "8 s"))
        self.action9_s.setText(_translate("MainWindow", "9 s"))
        self.action10_s.setText(_translate("MainWindow", "10 s"))
